name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      cucumberTag:
        description: 'Cucumber tag to run'
        required: true
        default: '@Login'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Tests
      run: mvn clean test -Dcucumber.filter.tags="${{ github.event.inputs.cucumberTag }}" -Dheadless

    - name: Generate HTML report
      run: mvn surefire-report:report

    - name: Upload Surefire Reports
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports/